### ISSUE TITLE
Simplify project source code hierarchy

### ISSUE THREAD

**Issue by diegobfernandez** [urbas/bud#12]
The directory where source code for projects reside COULD be shallower.
I don't think it MUST, but I would like to opt for something my team is used to.
If there were an option to use all C#(.cs) files under the project root it would be great.

**Comment by urbas** [comment]
There's a way to do this already. Here's how you can do it:

```csharp
new Project("foo",
            Cs.Dll(BuildDirsKeys.BaseDir.Modify(config => config.GetBaseDir(Project.ProjectKey(BudProjectId))))
```

It's quite a bit convoluted. This should be much easier to do. Maybe something like this:

```csharp
new Project("foo", Cs.Dll(BaseDir.SetToProjectRoot));
```

**Comment by diegobfernandez** [comment]
Nice! Thanks for the clarification.
One way or another I think this should be on docs!
Maybe a Wiki in this repository.

**Comment by diegobfernandez** [comment]
@ubas where is BudProjectId located.

**Comment by urbas** [comment]
Apologies, that was a copy-paste error. Replace `BudProjectId` with `"foo"` (the name of your project).

I have fixed the comment above too.
